"""Lámina C06 - ESPECIFICACIONES CONSTRUCTIVAS (notas estructurales).

Contenido de la lámina C10 de la referencia (RIVERGRAND) casi sin cambios, por indicación del
usuario [PR]. Ajustes: sin citas normativas (criterio de la A11), marcas comerciales con
"o similar", capacidad de suelo sin el informe de laboratorio de la referencia (a verificar con
estudio de suelos), sin madera estructural ni obras de retención (no se usan en esta vivienda).
"""
import cadlib as cl
import hoja as H

REV = "rev0"
OUT = cl.ROOT / "planos" / "C06_especificaciones"
NAME = f"SR-C06_ESPECIFICACIONES_{REV}"
LAYOUT = "C06-ESPECIFICACIONES"

doc = cl.new_doc()
psp = doc.layouts.new(LAYOUT)
psp.page_setup(size=(cl.A1_W, cl.A1_H), margins=(0, 0, 0, 0), units="mm")
doc.layouts.set_active_layout(LAYOUT)
cl.frame(psp)
HT, HN = 2.2, 2.3                                   # texto de tablas / notas


def head(x, y, t, size=3.2):
    cl.text(psp, t, (x, y), size, "A-TITULOS", "TOP_LEFT")
    return y - size - 3.0


def notes(x, y, lines, w):
    """Notas con estimación de altura conservadora (mayúsculas: ~0,95 h por carácter)."""
    import math
    cpl = max(10, int(w / (0.95 * HN)))
    for t in lines:
        n = max(1, math.ceil(len(t) / cpl))
        cl.mtext(psp, t, (x, y), HN, w, attach=1, spacing=1.0)
        y -= n * HN * 1.55 + 0.6 * HN
    return y - 4.0


# ---------------------------------------------------------------- columna 1: ganchos y dobleces
X1, W1 = 35.0, 160.0
cl.text(psp, "NOTAS ESTRUCTURALES Y ESPECIFICACIONES CONSTRUCTIVAS [PR]", (X1, 575.0), 5.0,
        "A-TITULOS", "TOP_LEFT")
y = head(X1, 562.0, "DIMENSIONES DE GANCHOS ESTÁNDAR (EN MILÍMETROS)")
rows = [["VARILLA", "Lg", "Rg", "Ltot MÍN.", "fy", "Lag", "fy", "Lag *"],
        ["", "(mm)", "(mm)", "(mm)", "(kg/cm²)", "f'c=210", "(kg/cm²)", "f'c=210"]]
data = [("#2", 80, 25, 105, 2800, 150, 150), ("#3", 115, 40, 155, 2800, 150, 175),
        ("#4", 150, 50, 200, 2800, 175, 250), ("#5", 190, 65, 255, None, None, 300),
        ("#6", 230, 75, 305, None, None, 350), ("#7", 265, 90, 355, None, None, 400),
        ("#8", 305, 100, 405, None, None, 475), ("#9", 350, 150, 500, None, None, 550),
        ("#10", 390, 160, 550, None, None, 600), ("#11", 430, 180, 610, None, None, 650)]
for v, lg, rg, lt, fy, lag, lag2 in data:
    rows.append([v, str(lg), str(rg), str(lt), str(fy) if fy else "-", str(lag) if lag else "-",
                 "4200", str(lag2)])
y = cl.table(psp, X1, y, [17, 18, 18, 22, 20, 21, 20, 24], rows, row_h=6.0, h=HT)
y = notes(X1, y - 2.0, [
    "* SE PERMITE UTILIZAR UN FACTOR DE REDUCCIÓN DE 0,95 EN EL VALOR DE Lag PARA LAS VARILLAS "
    "#5 A #11 CUANDO SE UTILICE CONCRETO CON RESISTENCIA A LA COMPRESIÓN DE 245 kg/cm², Y DE "
    "0,85 CUANDO SE UTILICE CONCRETO DE 280 kg/cm².",
    "Lg: LONGITUD DEL GANCHO; Rg: RADIO DE DOBLEZ; Ltot: LONGITUD TOTAL; Lag: LONGITUD DE "
    "ANCLAJE CON GANCHO."], W1)
y = head(X1, y, "DIMENSIONES DE DOBLECES PARA AROS Y ESTRIBOS")
rows = [["ARO", "Rs MÍNIMO (mm)", "Ls MÍNIMO (mm)", "Ltot (mm)"],
        ["#2", "15", "75", "95"], ["#3", "20", "75", "105"], ["#4", "25", "50", "115"]]
y = cl.table(psp, X1, y, [25, 45, 45, 45], rows, row_h=6.0, h=HT)
y = notes(X1, y - 2.0, ["DOBLEZ DE 135° PARA AROS Y ESTRIBOS."], W1)
y = head(X1, y - 2.0, "NOTAS GENERALES", 3.5)
y = notes(X1, y, [
    "1.- EN ESTA LÁMINA LAS MEDIDAS SE PRESENTAN EN MILÍMETROS, A MENOS QUE SE INDIQUE LO "
    "CONTRARIO.",
    "2.- EN TODA JUNTA DE COLADO, PLANEADA O NO, SE DEBERÁ COLOCAR UN \"WATERSTOP\" APROPIADO "
    "PARA EL TIPO DE JUNTA A REALIZAR. EL \"WATERSTOP\" DEBERÁ SER APROBADO POR LA INSPECCIÓN "
    "PREVIO A SU COLOCACIÓN.",
    "3.- EL CONTRATISTA ELECTROMECÁNICO DEBERÁ SOLICITAR EL VISTO BUENO DE LA INSPECCIÓN ANTES "
    "DE COLOCAR, CONSTRUIR O PERFORAR PASANTES EN MUROS DE CONCRETO Y MAMPOSTERÍA, VIGAS Y "
    "COLUMNAS DE CONCRETO REFORZADO, VIGAS Y COLUMNAS DE ACERO ESTRUCTURAL, ENTREPISOS Y "
    "CUALQUIER OTRO ELEMENTO ESTRUCTURAL.",
    "4.- TODOS LOS TUBOS DE ACERO (VIGAS Y LARGUEROS) DEBEN LLEVAR UNA TAPA DE CIERRE, SOLDADA "
    "DE MANERA CONTINUA, CON TAL DE PROTEGER EL INTERIOR DEL TUBO ANTE LA CORROSIÓN.",
    "5.- IMPERMEABILIZACIÓN.",
    "6.- CUANDO SE REALICE ALGUNA EXCAVACIÓN CON UNA PROFUNDIDAD SUPERIOR A 1,5 m SE DEBEN TOMAR "
    "MEDIDAS PARA PROTEGER LAS ESTRUCTURAS CIRCUNDANTES Y COLOCAR ADEMES EN LA EXCAVACIÓN.",
    "7.- PARA LA CONSTRUCCIÓN DE RELLENOS O SUSTITUCIONES SE DEBE REALIZAR COMPACTACIÓN EN CAPAS "
    "DE MÁXIMO 200 mm."], W1)

# ---------------------------------------------------------------- columna 2: traslapes y recubrimientos
X2, W2 = 210.0, 165.0
y = head(X2, 562.0, "LONGITUD MÍNIMA DE TRASLAPE EN CONCRETO (EN MILÍMETROS)")
rows = [["VARILLA", "Fy=2800 kg/cm² GR.40", None, "Fy=4200 kg/cm² GR.60", None],
        ["", "LECHO SUP.", "LECHO INF.", "LECHO SUP.", "LECHO INF."]]
tras = [("#2", 700, 500, 700, 500), ("#3", 700, 500, 800, 600), ("#4", 700, 500, 1050, 750),
        ("#5", 900, 650, 1350, 1000), ("#6", 1100, 800, 1600, 1150), ("#7", 1250, 900, 1900, 1350),
        ("#8", 1450, 1050, 2150, 1550), ("#9", 1600, 1150, 2400, 1750),
        ("#10", 1800, 1300, 2700, 1950), ("#11", 2000, 1400, 2950, 2100)]
rows += [[v] + [str(a) for a in r] for v, *r in tras]
y = cl.table(psp, X2, y, [21, 36, 36, 36, 36], rows, row_h=6.0, h=HT)
y = notes(X2, y - 2.0, [
    "1.- EL REFUERZO DE LECHO SUPERIOR ES TODO AQUEL REFUERZO QUE SEA COLOCADO SOBRE AL MENOS "
    "30 cm DE CONCRETO COLADO EN SITIO.",
    "2.- ESTAS LONGITUDES DE TRASLAPE SON VÁLIDAS PARA LAS SIGUIENTES CONDICIONES: "
    "RECUBRIMIENTO MÍNIMO AL ARO SEGÚN LA TABLA DE RECUBRIMIENTOS MÍNIMOS; RESISTENCIA MÍNIMA "
    "DEL CONCRETO A LA COMPRESIÓN f'c = 210 kg/cm².",
    "3.- PARA LAS VARILLAS DE #5 A #11 SE PERMITE APLICAR UN FACTOR DE REDUCCIÓN DE 0,95 EN LOS "
    "VALORES DE LA TABLA CUANDO SE UTILICE CONCRETO CON RESISTENCIA A LA COMPRESIÓN DE "
    "245 kg/cm², Y DE 0,85 CUANDO SE UTILICE CONCRETO DE 280 kg/cm².",
    "4.- NO SE PERMITE EL TRASLAPE SIMULTÁNEO DE MÁS DEL 50 % DE LAS VARILLAS DE UN MISMO LECHO.",
    "5.- LAS VARILLAS DE LECHO SUPERIOR DEBEN SER EMPALMADAS EN EL CENTRO DE LOS CLAROS Y LAS "
    "VARILLAS DEL LECHO INFERIOR A 1/4 DE LA DISTANCIA LIBRE ENTRE LOS APOYOS MEDIDA DESDE EL "
    "EXTREMO DEL ELEMENTO.",
    "6.- EN CASO DE NO CUMPLIR CON LAS CONDICIONES ANTERIORES, LAS LONGITUDES DE TRASLAPE "
    "MOSTRADAS EN LA TABLA DEBEN SER AUMENTADAS EN UN 30 %.",
    "7.- LA SEPARACIÓN ENTRE LOS TRASLAPES DE LAS VARILLAS INDIVIDUALES DE UN PAQUETE DEBE SER "
    "DE 1000 mm COMO MÍNIMO.",
    "8.- EN ZONAS DE TRASLAPE LOS AROS TENDRÁN UNA SEPARACIÓN MÁXIMA DE 100 mm.",
    "9.- NO SE PERMITEN TRASLAPES DENTRO DE UNIONES NI DENTRO DE UNA DISTANCIA IGUAL A DOS "
    "VECES EL PERALTE DE LA VIGA MEDIDA A PARTIR DE AMBOS EXTREMOS DEL ELEMENTO.",
    "10.- NO SE PERMITEN TRASLAPES EN LAS BARRAS LONGITUDINALES DE REFUERZO DE PAREDES DE "
    "MAMPOSTERÍA. LOS ANCLAJES SE HARÁN ÚNICAMENTE EN LAS COLUMNAS.",
    "11.- EL PLANO DE ARMADO DE TALLER DEBE SER APROBADO POR EL DISEÑADOR ANTES DE INICIAR EL "
    "ARMADO EN SITIO."], W2)
y = head(X2, y - 2.0, "RECUBRIMIENTO MÍNIMO PARA ELEMENTOS DE CONCRETO REFORZADO")
rows = [["ELEMENTO ESTRUCTURAL", "RECUBRIMIENTO (mm)"], ["MUROS Y LOSAS", "40"],
        ["VIGAS Y COLUMNAS", "40"], ["PLACAS DE FUNDACIÓN", "50"],
        ["ELEMENTOS COLADOS CONTRA EL TERRENO", "75"]]
y = cl.table(psp, X2, y, [95, 50], rows, row_h=6.0, h=HT)
y = notes(X2, y - 2.0, [
    "1.- EL RECUBRIMIENTO SE MIDE DESDE LA SUPERFICIE DEL CONCRETO HASTA EL BORDE EXTERIOR DEL ARO.",
    "2.- EN ELEMENTOS ARMADOS SIN AROS, EL RECUBRIMIENTO SE MIDE DESDE LA SUPERFICIE DEL "
    "CONCRETO HASTA EL BORDE EXTERIOR DEL REFUERZO.",
    "3.- ESTOS RECUBRIMIENTOS MÍNIMOS SON VÁLIDOS PARA CONDICIONES DE FUNCIONAMIENTO NORMALES. "
    "SI LAS CONDICIONES SON MÁS AGRESIVAS, O A LA INTEMPERIE, EL RECUBRIMIENTO DEBE AUMENTARSE "
    "SEGÚN LO INDIQUE EL DISEÑADOR.",
    "4.- SI EL CONCRETO SE COLOCA DIRECTAMENTE SOBRE EL TERRENO, SE USARÁ UN RECUBRIMIENTO "
    "MÍNIMO DE 75 mm."], W2)

# ---------------------------------------------------------------- columna 3: materiales, cimentaciones, apuntalamiento
X3, W3 = 390.0, 150.0
y = head(X3, 562.0, "NOTAS DE MATERIALES", 3.5)
y = notes(X3, y, [
    "1.- EN TODAS LAS ESTRUCTURAS DE CONCRETO COLADO EN OBRA SE DEBE LLEVAR A CABO EL PROCESO "
    "DE CURADO DEL CONCRETO DURANTE AL MENOS 8 DÍAS.",
    "2.- PARA LAS MEZCLAS DE CONCRETO SE PERMITE UN TAMAÑO MÁXIMO DE AGREGADO DE 25 mm.",
    "3.- EL REVENIMIENTO DE LA MEZCLA DE CONCRETO DEBE SER MEDIDO PREVIO A LA COLOCACIÓN Y NO "
    "DEBE SOBREPASAR LOS 100 mm PARA MEZCLAS SIN ADITIVOS.",
    "4.- PARA REALIZAR REPARACIONES EN ESTRUCTURAS DE CONCRETO POR DEFECTOS, HORMIGUEROS O "
    "CAVIDADES SE DEBE UTILIZAR MORTERO DE REPARACIÓN TIPO EXPANSIVO O DE CONTRACCIÓN. NO SE "
    "PERMITE LA REPARACIÓN DE NINGÚN ELEMENTO SIN LA APROBACIÓN DE LA INSPECCIÓN.",
    "5.- CUANDO SEA NECESARIO REALIZAR REPARACIONES SE DEBE PICAR LA SECCIÓN DEFECTUOSA, "
    "ELIMINAR EL MATERIAL SUELTO Y COLOCAR UN IMPRIMANTE DE EPÓXICO COMPRENSIBLE PREVIO A LA "
    "COLOCACIÓN DEL MORTERO DE REPARACIÓN.",
    "6.- EN LOS LUGARES QUE SE INDIQUE LA COLOCACIÓN DE PLACAS DE ANCLAJE EN PLANOS SE DEBE "
    "UTILIZAR MORTERO DE NIVELACIÓN TIPO MASTER FLOW O SIMILAR, CON RESISTENCIA MÍNIMA DE "
    "400 kg/cm² A LOS 28 DÍAS.",
    "7.- EL ANCLAJE DE BARRAS DE ACERO O DOVELAS DEBE REALIZARSE CON EPÓXICO TIPO RE-50SD DE "
    "HILTI O SIMILAR, PREVIA APROBACIÓN DE LA INSPECCIÓN. PREVIO A LA COLOCACIÓN DEL EPÓXICO, "
    "LAS PERFORACIONES DEBEN ESTAR LIMPIAS Y LIBRES DE SUCIEDAD O POLVO. LA INYECCIÓN DEL "
    "MATERIAL EPÓXICO DEBE HACERSE CON EL EQUIPO ESPECIAL INDICADO POR EL FABRICANTE Y "
    "APROBADO POR LA INSPECCIÓN.",
    "8.- EL ESPESOR MÍNIMO DE SOBRELOSA PARA LOS DIFERENTES SISTEMAS DE CONTRAPISO "
    "PREFABRICADO ES DE 70 mm.",
    "9.- LA CONTRAFLECHA MÁXIMA PERMITIDA PARA LOS ELEMENTOS PREFABRICADOS DEL SISTEMA DE "
    "ENTREPISO ES DE -0 mm / +25 mm."], W3)
y = head(X3, y - 2.0, "CIMENTACIONES", 3.5)
y = notes(X3, y, [
    "LAS FUNDACIONES SE COLOCARÁN SOBRE UNA PRIMERA CAPA DE MATERIAL SELECTO COMPACTADO AL 95 % "
    "PROCTOR ESTÁNDAR APROBADO POR EL INSPECTOR. LOS PISOS SE COLOCARÁN SOBRE UNA CAPA DE LASTRE "
    "COMPACTADO AL 95 % PROCTOR MODIFICADO.",
    "EL NIVEL DE DESPLANTE SERÁ EL INDICADO EN LOS DETALLES DE FUNDACIÓN (C02).",
    "PARA EL CÁLCULO DE LAS FUNDACIONES PRINCIPALES SE TOMÓ UNA CAPACIDAD DE SOPORTE ADMISIBLE "
    "DEL SUELO qadm = 12 ton/m² CON UN F.S. = 3. VALOR A VERIFICAR CON EL ESTUDIO DE SUELOS DE "
    "ESTE PROYECTO (PD).",
    "EL CONTRATISTA DEBE LLEGAR A LAS PROFUNDIDADES INDICADAS Y LAS PLACAS SE COLOCARÁN SOBRE "
    "SUELOS NATURALES PREPARADOS ADECUADAMENTE O SOBRE RELLENOS ESTRUCTURALES COMPACTADOS "
    "EXTENDIÉNDOSE HASTA SUELOS NATURALES."], W3)
y = head(X3, y - 2.0, "NOTAS DE APUNTALAMIENTO DE VIGAS Y VIGUETAS DE ENTREPISO", 3.0)
y = notes(X3, y, [
    "EN VIGAS O VIGUETAS CUYA LONGITUD SEA MAYOR A 4,0 m SE REQUIERE APUNTALAMIENTO TEMPORAL A "
    "L/3 DE LOS EXTREMOS DE LA VIGA.",
    "EN LAS VIGAS O VIGUETAS CUYA LONGITUD SEA MENOR A 4,0 m SE REQUIERE APUNTALAMIENTO "
    "TEMPORAL A L/2 DE LOS EXTREMOS DE LA VIGA.",
    "LOS PUNTALES DEBEN SER CAPACES DE SOPORTAR EL PESO PROPIO DE LA VIGA O VIGUETA, MÁS EL PESO "
    "DE LA LOSA Y LAS CARGAS DE CONSTRUCCIÓN.",
    "LOS PUNTALES PODRÁN REMOVERSE HASTA 10 DÍAS (MÍNIMO) DESPUÉS DE COLADO EL ENTREPISO."], W3)

# ---------------------------------------------------------------- columna 4: especificaciones de materiales
X4, W4 = 555.0, 150.0
y = head(X4, 562.0, "ESPECIFICACIONES TÉCNICAS DE MATERIALES", 3.5)
for sub, lines in (
    ("CONCRETO", [
        "RESISTENCIA A LA COMPRESIÓN MEDIDA EN CILINDROS DE 150 x 300 mm A LOS 28 DÍAS:",
        "PLACAS DE FUNDACIÓN: f'c = 245 kg/cm².",
        "LOSAS DE ENTREPISO, VIGAS Y COLUMNAS: f'c = 245 kg/cm².",
        "RELLENO DE CELDAS DE BLOQUES: f'c = 175 kg/cm².",
        "ELEMENTOS DE CONCRETO PREFABRICADO: 280 kg/cm² O SUPERIOR SEGÚN RECOMENDACIÓN DEL "
        "FABRICANTE."]),
    ("ACERO DE REFUERZO", [
        "BARRAS #3 Y #4 SERÁN ACERO GRADO 60, ESPECIFICACIÓN ASTM A-706, fy = 4200 kg/cm².",
        "BARRAS DE #5 A #10 SERÁN ACERO GRADO 60, ESPECIFICACIÓN ASTM A-706, fy = 4200 kg/cm²."]),
    ("BLOQUES DE CONCRETO", [
        "BLOQUES DE CONCRETO CLASE A. RESISTENCIA MEDIDA SOBRE EL ÁREA NETA A LOS 28 DÍAS: "
        "PROMEDIO DE 3 MUESTRAS 140 kg/cm²; VALOR MÍNIMO 120 kg/cm² DE UN TESTIGO."]),
    ("ACERO ESTRUCTURAL", [
        "PERFILES ROLADOS EN CALIENTE SEGÚN ESPECIFICACIÓN ASTM A-572 / A-992 GRADO 50: "
        "ESFUERZO MÍNIMO DE FLUENCIA fy = 3515 kg/cm².",
        "ELEMENTOS ESTRUCTURALES A BASE DE LÁMINAS DE ACERO SEGÚN ESPECIFICACIÓN ASTM A-36: "
        "fy = 2535 kg/cm².",
        "ELEMENTOS DE ACERO TUBULAR LAMINADOS EN CALIENTE SEGÚN ESPECIFICACIÓN ASTM A-500B: "
        "fy = 3234 kg/cm².",
        "ELEMENTOS DE ACERO TUBULAR PIPE ESTÁNDAR SEGÚN ESPECIFICACIÓN ASTM A-53 GRADO B: "
        "fy = 2460 kg/cm².",
        "PERFILES DELGADOS DOBLADOS EN FRÍO SEGÚN JIS G-3132 SPHT 2: fy = 2310 kg/cm².",
        "PLACAS DE ANCLAJE DE ACERO SEGÚN ESPECIFICACIÓN ASTM A-36: fy = 2535 kg/cm²."]),
    ("SOLDADURA", [
        "TODAS LAS SOLDADURAS ESTRUCTURALES EN TALLER O EN CAMPO SERÁN SMAW CON ELECTRODOS "
        "E6013 PARA LARGUEROS DE TECHO Y CERCHAS DE TECHO.",
        "ES PERMITIDO UTILIZAR UN PROCESO GMAW CON ELECTRODOS CONTINUOS ÚNICAMENTE EN TALLER."]),
    ("PINTURA DE UNIONES", [
        "LAS SUPERFICIES DE UNIÓN DE LOS ELEMENTOS ESTRUCTURALES DE ACERO DEBEN TRATARSE CON "
        "PINTURA INORGÁNICA DE ZINC, ESPESOR DE 2 mil (50 MICRAS)."])):
    y = head(X4 + 3.0, y - 1.0, sub, 2.6)
    y = notes(X4 + 3.0, y, lines, W4 - 3.0)

cl.notes_block(psp, X4, 70.0, [
    "TODAS LAS NOTAS DE ESTA LÁMINA SON LAS DEL PROYECTO DE REFERENCIA, POR INDICACIÓN DEL "
    "INGENIERO RESPONSABLE, Y NO SUSTITUYEN LA MEMORIA DE CÁLCULO. [PR]",
    cl.NOTA_PR], 1.9, W4)

H.titleblock(doc, psp, "C06", "ESPECIFICACIONES",
             ["CONSTRUCTIVAS.", "NOTAS ESTRUCTURALES.", "GANCHOS, TRASLAPES Y RECUBRIMIENTOS.",
              "MATERIALES.", "", ""],
             [("0", "06-10-2026", "VERSIÓN DE TRABAJO PARA REVISIÓN")], escalas="S/E")

OUT.mkdir(parents=True, exist_ok=True)
doc.saveas(OUT / f"{NAME}.dxf")
cl.render_pdf(doc, LAYOUT, OUT / f"{NAME}.pdf")
print("DXF:", OUT / f"{NAME}.dxf")
